# Generated by Django 4.2 on 2024-05-11 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='cedula',
            field=models.CharField(default='000-0000000-0', max_length=20),
        ),
        migrations.AddField(
            model_name='record',
            name='fecha_nacimiento',
            field=models.DateField(default='1900-01-01'),
        ),
        migrations.AddField(
            model_name='record',
            name='last_name_2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='sexo',
            field=models.BinaryField(default=None),
        ),
    ]
