# Generated by Django 4.2 on 2024-05-11 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0002_record_cedula_record_fecha_nacimiento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='sexo',
            field=models.BinaryField(blank=True, default=None, null=True),
        ),
    ]
