# Generated by Django 4.2 on 2024-05-16 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0004_record_direccion_madre_record_direccion_padre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='country',
            field=models.CharField(choices=[('Dominican Republic', 'Dominican Republic'), ('Haiti', 'Haiti'), ('Jamaica', 'Jamaica'), ('USA', 'USA'), ('Costa Rica', 'Costa Rica'), ('Paraguay', 'Paraguay')], max_length=125),
        ),
        migrations.AlterField(
            model_name='record',
            name='fecha_nacimiento',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='record',
            name='sexo',
            field=models.CharField(choices=[('Hombre', 'Hombre'), ('Mujer', 'Mujer')], max_length=10),
        ),
    ]
